on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI
jobs:
  cargo_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - json,hyper_1
          - json,hyper_0_14
          - hyper_1
          - hyper_0_14
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo fmt
        run: cargo fmt --all -- --check
      - name: cargo clippy
        run: cargo clippy --no-default-features --features ${{ matrix.features }}
      - name: cargo test
        run: cargo test --no-default-features --features ${{ matrix.features }}